### ISSUE TITLE
Binding generator doesn't work anymore, duplicate enum definition is created.

### ISSUE THREAD

**Issue by AllenDang** [AllenDang/cimgui-go#113]
I'm trying to update imgui to 1.89.4 manually, and noticed that ImGuiModFlags has duplicate definition which will break the build.

I did a quick check about gencpp.go and didn't get luck.

@gucio321 Do you have any clue about it?

**Comment by gucio321** [comment]
Will have one a bit later today.
Will investigate as soon as i come back home.

**Comment by gucio321** [comment]
@AllenDang could you push faulty code to some branch; i will be easier for me to debug

**Comment by gucio321** [comment]
@AllenDang I can't see the crash unfortunetly...
I'm at 684d8294de592bada96e21f59a18e65187fb51c7
After running `make` everything compiles fine

**Comment by AllenDang** [comment]
@gucio321 You need to run `cd cimgui/generator; ./generator.sh` and `make cimgui` to regenerate the binding.

**Comment by gucio321** [comment]
I see, here is an error I'm getting now:
```
[examples (0) ]$ go run -a .
# github.com/AllenDang/cimgui-go
In file included from ./cimgui_wrapper.h:6,
                 from ./backend.h:3,
                 from ../backend.go:20:
./cimgui/cimgui.h:148:15: error: expected identifier or '(' before ':' token
  148 | enum ImGuiKey : int;
      |               ^
./cimgui/cimgui.h:1439:18: error: expected identifier or '(' before ':' token
 1439 | enum ImGuiLocKey : int;
      |                  ^
[examples (1) ]$ 
```

**Comment by gucio321** [comment]
@AllenDang so I did two notes:
- most recent cimgui version is supposed to work with 1.89.3 (nor 1.89.4) and it _may contain_ some bugs probably
- I am not sure what cimgui version are we exactly using, but I suppose you should upgrade the whole dependency instead of just imgui.

Thats why I wanted to develop something like in https://github.com/AllenDang/cimgui-go/pull/100

**Comment by AllenDang** [comment]
@gucio321 Yeah, maybe we need to update cimgui version as well...

**Comment by gucio321** [comment]
Yeah, that's what i think we should do first, however in not sure how since simple drop in doesn't seem to work and I'm not sure about modifications that needs to be made to make it working

**Comment by sonoro1234** [comment]
> * I am not sure what cimgui version are we exactly using, but I suppose you should upgrade the whole dependency instead of just imgui

Sure

**Comment by gucio321** [comment]
@AllenDang I suppose that #100 might become a fix for that since it will re-generate everything **and** generation will be fully automated.

**Comment by AllenDang** [comment]
@gucio321 I met a incompatible issue between implot and imgui at last week end. I intended to upgrade imgui since it has a new release, after finished, I found out that implot doesn't work with. the newest version.
If we created a auto-update, I don't think we could maintain the compatibility between imgui and other libs like implot.

**Comment by gucio321** [comment]
> And BTW this issue is fixed with newest cimgui's lua generator.

Awesome!

> @gucio321 I met a incompatible issue between implot and imgui at last week end. I intended to upgrade imgui since it has a new release, after finished, I found out that implot doesn't work with. the newest version.
If we created a auto-update, I don't think we could maintain the compatibility between imgui and other libs like implot.

hmm, quite interessting. However please note, that by "auto update" I don't mean a workflow periodically making weird pushes to master. I mean just a Makefile rule that allows you to execute `make update`, check whether everything works fine and commit. It would be, in my opinion, easier to maintain the code this way.

**Comment by sonoro1234** [comment]
> I found out that implot doesn't work with. the newest version.

with implot last commit https://github.com/epezent/implot/commit/33c5a965f55f80057f197257d1d1cdb06523e963 it should be solved

**Comment by gucio321** [comment]
@AllenDang I think the base issue is resolved already, so closing this.
